export const BrandActionsTypes = {
  SET_BRANDS: "SET_BRANDS",
  DELETE_BRANDS: "DELETE_BRANDS",
  ADD_BRAND: "ADD_BRAND",
  UPDATE_BRAND: "UPDATE_BRAND",
  SET_BRANDS_TOTAL_PAGES: "SET_BRANDS_TOTAL_PAGES",
  SET_BRANDS_PAGE: "SET_BRANDS_PAGE",
  SET_BRANDS_SEARCH_NAME: "SET_BRANDS_SEARCH_NAME",
};
