export const ProductActionsTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  SET_PRODUCTS_TOTAL_PAGES: "SET_PRODUCTS_TOTAL_PAGES",
  SET_PRODUCTS_PAGE: "SET_PRODUCTS_PAGE",
};
