export const CategoryActionsTypes = {
  SET_CATEGORIES: "SET_CATEGORIES",
  DELETE_CATEGORIES: "DELETE_CATEGORIES",
  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  SET_CATEGORIES_TOTAL_PAGES: "SET_CATEGORIES_TOTAL_PAGES",
  SET_CATEGORIES_PAGE: "SET_CATEGORIES_PAGE",
  SET_CATEGORIES_SEARCH_NAME: "SET_CATEGORIES_SEARCH_NAME",
  SET_CATEGORIES_SEARCH_DESCRIPTION: "SET_CATEGORIES_SEARCH_DESCRIPTION",
};
